### ISSUE TITLE
Issue on moves result

### ISSUE THREAD

**Issue by Soyn** [livoras/list-diff#8]
**Do you want to request a feature or report a bug?**
  Bug
**What is the current behavior?**
```javascript
  var before = [{id: 1}, {id: 2}, {id: 3}, {id: 4}, {id: 5}, {id: 6}]
  var after = [];
  var diffs = diff.diff(before, after, 'id'); 
```
```javascript
      //  In this case the moves is:
      { index: 0, type: 0 },
      { index: 0, type: 0 },
      { index: 0, type: 0 },
      { index: 0, type: 0 },
      { index: 0, type: 0 },
      { index: 0, type: 0 }
```

  But i don't think the output like above is right. Maybe you want to enable these moves like this for convenience.

```javascript
  for(let i = 0; i < moves.length; i +=1) {
    if(moves.type ===  REMOVE) {
        // remove element in old list
    }
  }
```
 It make me confused, cause will should list the action from old list to new list. In my option, like its name, we list the diffs from old list to new list, below moves should be right:

**What is the expected behavior?**
```javascript
  [
      { index: 0, type: 0 },
      { index: 1, type: 0 },
      { index: 2, type: 0 },
      { index: 3, type: 0 },
      { index: 4, type: 0 },
      { index: 5, type: 0 }
    ]
```

**P.S: If you need, i will send you a pr.**

**Comment by livoras** [comment]
The output actually reflects the process that how you should maintain your list over time instead of the what happpened on the original list.

In your example, always removing the first item in the list over time results in making a empty list which  perfectly matches the expectation.

```
[1, 2,3 ] remove position 0, => [2, 3]
[2, 3] remove position 0, => [3]
[3] remove position 0, => []
```

The purpose of this library is giving you the actions how you can maintain your list *overtime*.

**Comment by Soyn** [comment]
Ok. Thanks. I will close this issue.
